"""empty message

Revision ID: 205b64a1b857
Revises: 00b58322a038
Create Date: 2019-04-12 09:52:13.521351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205b64a1b857'
down_revision = '00b58322a038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carousel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cover_img', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carousel')
    # ### end Alembic commands ###
