"""empty message

Revision ID: 652183becfef
Revises: bfae8ee4b8d7
Create Date: 2019-01-16 16:36:29.289267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652183becfef'
down_revision = 'bfae8ee4b8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name1', sa.String(length=128), nullable=True),
    sa.Column('name2', sa.String(length=11), nullable=True),
    sa.Column('name3', sa.String(length=128), nullable=True),
    sa.Column('name4', sa.String(length=128), nullable=True),
    sa.Column('name5', sa.String(length=128), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info')
    # ### end Alembic commands ###
