"""empty message

Revision ID: b1151f6adbb0
Revises: bfb0aad4cc31
Create Date: 2019-04-15 13:15:00.417532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1151f6adbb0'
down_revision = 'bfb0aad4cc31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('pwd', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'pwd')
    # ### end Alembic commands ###
