"""empty message

Revision ID: b9d5a106794d
Revises: 652183becfef
Create Date: 2019-01-16 17:01:36.164854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9d5a106794d'
down_revision = '652183becfef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name1', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('name2', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('name3', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('name4', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('name5', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('create_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
