"""empty message

Revision ID: bfae8ee4b8d7
Revises: d055024d24f6
Create Date: 2019-01-16 11:32:24.121135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfae8ee4b8d7'
down_revision = 'd055024d24f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_receive', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_receive')
    # ### end Alembic commands ###
