"""empty message

Revision ID: bfb0aad4cc31
Revises: 205b64a1b857
Create Date: 2019-04-15 13:10:33.088983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfb0aad4cc31'
down_revision = '205b64a1b857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('account', sa.String(length=128), nullable=False))
    op.drop_index('name', table_name='admin')
    op.drop_index('phone', table_name='admin')
    op.drop_column('admin', 'pwd')
    op.drop_column('admin', 'name')
    op.drop_column('admin', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('phone', mysql.VARCHAR(length=11), nullable=False))
    op.add_column('admin', sa.Column('name', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('admin', sa.Column('pwd', mysql.VARCHAR(length=128), nullable=False))
    op.create_index('phone', 'admin', ['phone'], unique=True)
    op.create_index('name', 'admin', ['name'], unique=True)
    op.drop_column('admin', 'account')
    # ### end Alembic commands ###
