"""empty message

Revision ID: d055024d24f6
Revises: d46ee638e1ad
Create Date: 2019-01-15 18:10:01.232170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd055024d24f6'
down_revision = 'd46ee638e1ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('amount', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
