"""empty message

Revision ID: dd4f2bd27522
Revises: bb9b6a04061e
Create Date: 2019-01-15 18:01:02.786009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4f2bd27522'
down_revision = 'bb9b6a04061e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('sumprice', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'sumprice')
    # ### end Alembic commands ###
