"""empty message

Revision ID: f6f6b3a10d0e
Revises: b9d5a106794d
Create Date: 2019-03-11 17:17:46.613248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6f6b3a10d0e'
down_revision = 'b9d5a106794d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('head_img', sa.String(length=255), nullable=False))
    op.drop_column('user', 'pwd')
    op.drop_column('user', 'is_super')
    op.drop_column('user', 'name')
    op.drop_column('user', 'update_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('update_at', mysql.DATETIME(), nullable=False))
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('user', sa.Column('is_super', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('pwd', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('user', 'head_img')
    # ### end Alembic commands ###
